name: proba
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  toast: ^0.3.0
  http: ^0.13.4
  fluttertoast: ^8.0.9
  get: ^4.6.5
  material_design_icons_flutter: ^7.0.7296
  choice: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
   #flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
